name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: dotnet build

  test:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: dotnet test

  deploy:
    needs: test
    runs-on: ubuntu-lastest
    steps:
      - name: Deploy
        run: echo TESTE

  # Executando containers via actions: 
  # https://docs.github.com/pt/actions/sharing-automations/creating-actions/creating-a-docker-container-action
  # https://docs.github.com/pt/actions/sharing-automations/creating-actions
  # https://docs.github.com/pt/actions/use-cases-and-examples
